# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :ui_test1 do
  	multi_scan(
  		clean: true,
  		code_coverage: true,
  		output_types: 'junit',
  		output_directory: './reports',
  		workspace: Dir.entries('..').select {|f| f=~ /.*\.xcworkspace/ }[0],
  		scheme:'DemoApp',
  		try_count: 3,
  		xcargs: "ONLY_ACTIVE_ARCH=YES",
  		output_files: 'UITestsA.junit',
  		parallel_testrun_count: 2,
  		reset_simulator: true,
  		prelaunch_simulator: true,
  		testplan: 'UITestsA',
  		fail_build: true)
  end

  lane :ui_test2 do
  	multi_scan(
  		clean: true,
  		code_coverage: true,
  		output_types: 'junit',
  		workspace: Dir.entries('..').select {|f| f=~ /.*\.xcworkspace/ }[0],
  		output_directory: './reports',
  		output_files: 'UITestsB.junit',
  		scheme:'DemoApp',
  		try_count: 3,
  		xcargs: "ONLY_ACTIVE_ARCH=YES",
  		parallel_testrun_count: 2,
  		reset_simulator: true,
  		prelaunch_simulator: true,
  		testplan: 'UITestsB',
  		fail_build: true)
  end
  lane :ui_test3 do
  	multi_scan(
  		clean: true,
  		code_coverage: true,
  		output_types: 'junit',
  		workspace:Dir.entries('..').select {|f| f=~ /.*\.xcworkspace/ }[0],
  		output_directory: './reports',
  		output_files: 'TestPlan2C.junit',
  		scheme:'SomeOtherScheme',
  		try_count: 3,
  		xcargs: "ONLY_ACTIVE_ARCH=YES",
  		parallel_testrun_count: 2,
  		reset_simulator: true,
  		prelaunch_simulator: true,
  		testplan: 'TestPlan2C',
  		fail_build: true)
  end

end
